services:
  - type: web
    name: hire-ai
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12   # Use a stable Python version Render supports
      - key: SECRET_KEY
        generateValue: true
      - key: MONGO_URI
        fromDatabase:
          name: hire-ai-db   # Correct for Render’s managed DB
          property: connectionString
      - key: N8N_WEBHOOK_URL
      - key: ADMIN_EMAIL
      - key: ADMIN_PASSWORD

databases:
  - name: hire-ai-db
    databaseName: hireai
    plan: free
